previewsEnabled: true
services:
    # core
    - type: web
      name: core
      region: ohio
      runtime: node
      rootDir: .
      buildCommand: ./bin/render-build.sh core
      startCommand: pnpm start --filter core
      envVars:
          - fromGroup: pubpub-core-prod-env
    # integration-instances
    - type: redis
      name: integration-instances
      region: ohio
      ipAllowList: [] # only allow internal connections
      maxmemoryPolicy: noeviction
    # integration-submissions
    - type: web
      name: integration-submissions
      region: ohio
      runtime: node
      rootDir: .
      buildCommand: ./bin/render-build.sh integration-submissions
      startCommand: pnpm start --filter integration-submissions
      envVars:
          - fromGroup: pubpub-integration-prod-env
          - key: REDIS_CONNECTION_STRING
            fromService:
                type: redis
                name: integration-instances
                property: connectionString
    # integration-evaluations
    - type: web
      name: integration-evaluations
      region: ohio
      runtime: node
      rootDir: .
      buildCommand: ./bin/render-build.sh integration-evaluations
      startCommand: pnpm start --filter integration-evaluations
      envVars:
          - fromGroup: pubpub-integration-prod-env
          - key: REDIS_CONNECTION_STRING
            fromService:
                type: redis
                name: integration-instances
                property: connectionString
databases:
    - name: core
      plan: standard
      postgresMajorVersion: 15
      region: ohio