previewsEnabled: true
services:
- type: web
  name: pubpub-v7-core
  runtime: node
  rootDir: .
  buildCommand: pnpm install; pnpm run build --filter core...
  startCommand: pnpm run start --filter core
  envVars:
    - fromGroup: pubpub-core-prod-env
      previewValue: pubpub-core-preview-env