previewsEnabled: false
services:
    # core
    - type: web
      name: core
      region: ohio
      runtime: node
      rootDir: .
      buildCommand: ./bin/render-build.sh core
      startCommand: pnpm --filter core start
      preDeployCommand: pnpm --filter core migrate-deploy
      envVars:
          - fromGroup: pubpub-core-prod-env
    # flock
    - type: worker
      name: flock
      region: ohio
      runtime: node
      rootDir: .
      buildCommand: ./bin/render-build.sh jobs
      startCommand: pnpm --filter jobs start 
      envVars:
          - fromGroup: pubpub-flock-prod-env
    # integration-submissions
    - type: web
      name: integration-submissions
      region: ohio
      runtime: node
      rootDir: .
      buildCommand: ./bin/render-build.sh integration-submissions
      startCommand: pnpm start --filter integration-submissions
      envVars:
          - fromGroup: pubpub-integration-prod-env
    # integration-evaluations
    - type: web
      name: integration-evaluations
      region: ohio
      runtime: node
      rootDir: .
      buildCommand: ./bin/render-build.sh integration-evaluations
      startCommand: pnpm start --filter integration-evaluations
      envVars:
          - fromGroup: pubpub-integration-prod-env
databases:
    - name: core
      plan: standard
      postgresMajorVersion: 15
      region: ohio
